services:
  - type: web
    name: mafia-game
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
